### ISSUE TITLE
Logfile flooding

### ISSUE THREAD

**Issue by KongMD-Steam** [GraysonnG/BlackMageMod#20]
I beat a boss, then was on the screen to choose a card. I then did an ALT+TAB and noticed that my logfile was getting flooded with data like this:

-0.39473516:0.66809124 | 83
0.39739043:-0.570354 | 83
0.6375531:-0.4189316 | 83
0.109564476:0.24363548 | 83
0.13452445:0.055006027 | 83
-0.07918808:-0.078642845 | 83
-0.06495449:-0.057216298 | 83
-0.264897:-0.13892177 | 83
-0.22944763:-0.20352146 | 83
-0.031734314:0.24924198 | 83
-0.22355048:-0.29330447 | 83
-0.20515506:0.15134753 | 83
-0.3357746:-0.22273362 | 83
0.4699747:0.17369139 | 83
-0.47188407:-0.19035 | 83

Hundreds of lines per second. I was not running with the ModTheSpire debug flag checked. Is this some debug logging that needs to be commented out?

**Comment by GraysonnG** [comment]
Yea its a debug log I left in by accident. I will remove it and upload a new version tonight.
