### ISSUE TITLE
Unleash Bugged

### ISSUE THREAD

**Issue by Selindrile** [GraysonnG/BlackMageMod#21]
While unleash indeed no longer makes you lose stacks of fire or ice at the end of your turn, the first fire or ice card you cast on your turn removes the stacks anyway, so if you have 5 ice stacks, and then play "Ice Strike", your ice stack count goes to 1.

**Comment by GraysonnG** [comment]
This is working as intended. However the wording on Unleash probably needs to be changed to prevent confusion.
