### ISSUE TITLE
Some minor things

### ISSUE THREAD

**Issue by Vlad-00003** [GraysonnG/BlackMageMod#3]
Heyo!
There is some strange things I've found:
1. Doublecast card. It's a power card, so it can't be exhausted, as it's already 1 time use. But it has "Exhaust" in the description =)
2. Hoarder run mod and the Exchange function. This looks more like a feature, but still - with this mod exchanges gives you 3 copies of the card, resulting in the ability to get almost infinite amount of cards...

**Comment by Vlad-00003** [comment]
Also - the Sheer Cold effect doesn't stack...

**Comment by GraysonnG** [comment]
1. Fixed the description thank you
2. I will look into that
3. Freeze isn't supposed to stack that would be OP. I changed the description to imply it doesn't stack.

**Comment by Vlad-00003** [comment]
Thanks! This is awsome class with a great mechanics. Really love it =^-^=
